-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 20:25:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eyetecdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eyetecdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eyetecdb` DEFAULT CHARACTER SET utf8 ;
USE `eyetecdb` ;

-- -----------------------------------------------------
-- Table `eyetecdb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `ap_paterno` VARCHAR(20) NOT NULL,
  `ap_materno` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyetecdb`.`Especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`Especialista` (
  `idEspecialista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `ap_paterno` VARCHAR(20) NOT NULL,
  `ap_materno` VARCHAR(20) NOT NULL,
  `cedula` VARCHAR(25) NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `edad` INT NOT NULL,
  `usuario` VARCHAR(25) NOT NULL,
  `contrasena` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idEspecialista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyetecdb`.`Prediagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`Prediagnostico` (
  `idPrediagnostico` INT NOT NULL AUTO_INCREMENT,
  `Especialista_idEspecialista` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `duracion` INT NULL,
  `tipo_estrabismo` VARCHAR(30) NOT NULL,
  `desviacion_der` FLOAT NOT NULL,
  `desviacion_izq` FLOAT NOT NULL,
  `dioptrias_prismaticas` FLOAT NOT NULL,
  `caracteristicas_der` VARCHAR(55) NULL,
  `caracteristicas_izq` VARCHAR(55) NULL,
  PRIMARY KEY (`idPrediagnostico`, `Especialista_idEspecialista`, `Paciente_idPaciente`),
  CONSTRAINT `fk_Prediagnostico_Especialista1`
    FOREIGN KEY (`Especialista_idEspecialista`)
    REFERENCES `eyetecdb`.`Especialista` (`idEspecialista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Prediagnostico_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `eyetecdb`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyetecdb`.`Tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`Tratamiento` (
  `idTratamiento` INT NOT NULL AUTO_INCREMENT,
  `Especialista_idEspecialista` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `TipoDeTratamiento` VARCHAR(25) NOT NULL,
  `puntuacion` VARCHAR(20) NULL,
  `duraciontotal` VARCHAR(20) NOT NULL,
  `fecha` DATE NOT NULL,
  `nivel_de_mejora` VARCHAR(15) NULL,
  PRIMARY KEY (`idTratamiento`, `Especialista_idEspecialista`, `Paciente_idPaciente`),
  CONSTRAINT `fk_Tratamiento_Especialista1`
    FOREIGN KEY (`Especialista_idEspecialista`)
    REFERENCES `eyetecdb`.`Especialista` (`idEspecialista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tratamiento_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `eyetecdb`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyetecdb`.`DireccionPaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`DireccionPaciente` (
  `Paciente_idPaciente` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numeroINT` INT NULL,
  `numeroEXT` INT NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Paciente_idPaciente`),
  CONSTRAINT `fk_DireccionPaciente_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `eyetecdb`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyetecdb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`Telefono` (
  `Paciente_idPaciente` INT NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`Paciente_idPaciente`, `Telefono`),
  CONSTRAINT `fk_Telefono_Paciente`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `eyetecdb`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyetecdb`.`Diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`Diagnostico` (
  `Especialista_idEspecialista` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `tipo_estrabismo` VARCHAR(30) NOT NULL,
  `caracteristicas` VARCHAR(80) NULL,
  `observaciones` VARCHAR(80) NULL,
  PRIMARY KEY (`Especialista_idEspecialista`, `Paciente_idPaciente`),
  CONSTRAINT `fk_Diagnostico_Especialista1`
    FOREIGN KEY (`Especialista_idEspecialista`)
    REFERENCES `eyetecdb`.`Especialista` (`idEspecialista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Diagnostico_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `eyetecdb`.`Paciente` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eyetecdb`.`api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eyetecdb`.`api` (
  `id` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  `idEspecialista` INT NOT NULL,
  `tiempo` INT NULL,
  `code` VARCHAR(45) NULL,
  `statusMessage` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
